language: node_js
node_js:
  - 8
cache:
  yarn: true
  directories:
    - node_modules
script:
  - yarn run lint
  - yarn run test-ci
  - yarn run build
deploy:
  provider: s3
  access_key_id: $ACCESS_KEY_ID
  secret_access_key: $SECRET_ACCESS_KEY
  bucket: binkpitch.me
  skip_cleanup: true
  region: ap-southeast-1
  local_dir: build
